# Generated by Django 5.2.2 on 2025-06-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeituraSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(auto_now_add=True)),
                ("hora", models.TimeField(auto_now_add=True)),
                ("umidade", models.FloatField()),
                ("temperatura", models.FloatField()),
                ("irrigacao_ativa", models.BooleanField()),
                ("nitrogenio", models.FloatField()),
                ("fosforo", models.FloatField()),
                ("potassio", models.FloatField()),
            ],
        ),
    ]
