# Generated by Django 5.2.2 on 2025-06-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_sensor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leiturasensor",
            name="luminosidade",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
